name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Chatmarks
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - jagcardenas

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen instead...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which AI platform were you using when the bug occurred?
      options:
        - ChatGPT (chat.openai.com)
        - ChatGPT (chatgpt.com)
        - Claude (claude.ai)
        - Grok (x.com)
        - Grok (grok.x.ai)
        - Extension popup
        - Extension options page
        - Not platform-specific
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Edge
        - Brave
        - Opera
        - Other Chromium-based browser
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of your browser are you using?
      placeholder: "e.g., Chrome 120.0.6099.199"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of Chatmarks are you using?
      placeholder: "e.g., 1.0.0 (found in chrome://extensions/)"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Select text '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Are there any errors in the browser console? (F12 → Console tab)
      placeholder: Paste any console errors here...
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or paste them...

  - type: checkboxes
    id: feature-area
    attributes:
      label: Feature Area
      description: Which features are affected by this bug?
      options:
        - label: Text selection
        - label: Bookmark creation
        - label: Bookmark navigation
        - label: Bookmark editing/deletion
        - label: Visual highlights
        - label: Keyboard shortcuts
        - label: Context menu
        - label: Extension popup
        - label: Extension options
        - label: Data persistence/storage

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Extension completely unusable)
        - High (Major functionality broken)
        - Medium (Some functionality impaired)
        - Low (Minor issue/cosmetic)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any other information that might help us understand the issue...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have provided all requested information
          required: true
        - label: I understand this is a free, open-source project maintained by volunteers
          required: true