name: ✨ Feature Request
description: Suggest a new feature or enhancement for Chatmarks
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - jagcardenas

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature you'd like to request...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: "As a user, I want to... so that I can..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe how you envision this feature working...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Bookmarking (creation, editing, deletion)
        - Navigation (jumping between bookmarks)
        - User Interface (visual improvements, new UI elements)
        - Platform Support (new AI platforms, better integration)
        - Keyboard Shortcuts (new shortcuts, customization)
        - Search & Filtering (finding bookmarks, organization)
        - Import/Export (data portability)
        - Accessibility (screen readers, keyboard navigation)
        - Performance (speed improvements, optimization)
        - Collaboration (sharing bookmarks, team features)
        - Other
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature support?
      multiple: true
      options:
        - ChatGPT (chat.openai.com)
        - ChatGPT (chatgpt.com)
        - Claude (claude.ai)
        - Grok (x.com)
        - Grok (grok.x.ai)
        - Extension popup
        - Extension options page
        - All platforms
        - Platform-agnostic

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Provide specific user stories for this feature
      placeholder: |
        - As a student, I want to... so that I can...
        - As a researcher, I want to... so that I can...
        - As a developer, I want to... so that I can...
      value: |
        - As a [user type], I want to [action] so that I can [benefit]
        - As a [user type], I want to [action] so that I can [benefit]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific criteria should be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
      value: |
        - [ ] 
        - [ ] 
        - [ ] 

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current workflow)
        - High (Would significantly improve experience)
        - Medium (Nice to have improvement)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (Small UI change, minor functionality)
        - Medium (New component, moderate functionality)
        - Complex (Major feature, significant architecture changes)
        - Unknown (Not sure about implementation complexity)

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative approaches you've considered...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups or screenshots to illustrate your feature request.
      placeholder: Drag and drop images here or describe the visual design...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or inspiration for this feature.
      placeholder: Links to similar features, additional use cases, etc...

  - type: checkboxes
    id: impact-areas
    attributes:
      label: Potential Impact Areas
      description: Which areas of the extension might this feature affect?
      options:
        - label: User Interface (UI changes)
        - label: Performance (speed, memory usage)
        - label: Security (permissions, data handling)
        - label: Privacy (data collection, storage)
        - label: Accessibility (screen readers, keyboard nav)
        - label: Browser compatibility
        - label: Platform integration (ChatGPT/Claude/Grok)
        - label: Data storage/migration
        - label: Testing requirements

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: This feature aligns with the project's zero-cost, privacy-first goals
          required: true
        - label: I understand this is a free, open-source project maintained by volunteers
          required: true
        - label: I would be willing to help test this feature if implemented
          required: false