name: Security Analysis

on:
  push:
    branches: [ main ]  # Only run on main branch pushes
  pull_request:
    branches: [ main ]  # Only for PRs to main
  schedule:
    # Run security scan weekly on Sunday at 3 AM UTC
    - cron: '0 3 * * 0'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Dependency vulnerability scan
        run: |
          echo "🔍 Checking for critical/high vulnerabilities..."
          npm audit --audit-level=high --json > audit-results.json || true
          
          if [ -s audit-results.json ]; then
            high=$(cat audit-results.json | jq '.metadata.vulnerabilities.high // 0')
            critical=$(cat audit-results.json | jq '.metadata.vulnerabilities.critical // 0')
            
            echo "High: $high, Critical: $critical"
            
            if [ "$high" -gt "0" ] || [ "$critical" -gt "0" ]; then
              echo "❌ Found high/critical vulnerabilities"
              echo "Run 'npm audit fix' to resolve"
              exit 1
            fi
          fi
          
          echo "✅ No high/critical vulnerabilities found"
          
      - name: Build and scan extension
        run: |
          npm run build
          
          # Check for sensitive patterns in build output
          echo "🔍 Scanning build for sensitive data..."
          patterns="api[_-]?key|secret|password|token|private[_-]?key"
          
          if grep -ri "$patterns" dist/ 2>/dev/null; then
            echo "❌ Sensitive data patterns detected in build"
            exit 1
          fi
          
          echo "✅ No sensitive data found in build"
          
      - name: Verify package integrity  
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "❌ package-lock.json missing"
            exit 1
          fi
          
          npm ci --dry-run
          echo "✅ Package integrity verified"

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'  # Skip on scheduled runs
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-and-quality
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build extension
        run: npm run build
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  secrets-detection:
    name: Secrets Detection
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only on PRs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}